openapi: 3.0.0
info:
  title: Hello World
  description: Hello World
  version: 0.0.1
servers:
- url: 'http://localhost:8080'
paths:
  /hello-world:
    get:
      summary: Hello world greeting
      description: Hello world greeting
      operationId: hello
      parameters:
      - name: name
        in: query
        description: The entity to greet
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful hello world
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
components:
  schemas:
    HelloWorld:
      type: object
      required:
      - hello
      properties:
        hello:
          type: string

